config/routes.rb
Bookpacker::Application.routes.draw do
  
 resources :books

end

app/models/book.rb
class Book < ActiveRecord::Base

 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  require 'nokogiri'
  # GET /books
  # GET /books.json
  def index
    @books = Book.all  
  end



  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id]) 
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  
  # POST /books
  # POST /books.json
  def create

    @book = Book.new(book_params)


    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render action: 'show', status: :created, location: @book }
      else
        format.html { render action: 'new' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params[:book]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  
  # Make my list of book shipping weights
  # This calls the create_box method to start the packing process
  def ship_weight_list(books)
    @weights = []
    books.each do |book|       
      @weights << book.ship_weight     
    end 
    @boxes = []
    create_box(1, 0)
  end

  # This creates a box which is a hash with a number, the boxes total weight, and the boxes contents (in this case the books that will be shipped in this box)
  def create_box(id, weight)        
    box = {"box" => {"id" => id, "total_weight" => weight, "contents" => []}}
    @boxes << box      
    pack_books
  end

  
  # This adds up the books' weights and determines which box the books need to be placed. This also adds all the content information for each book that is added to the box. This will be used in the JSON output. 
  def pack_books       
    @weights.each_with_index do  |weight, index|
      box = @boxes.last
      sum = weight.to_f + box["box"]["total_weight"]
      if  sum <= 10
        box["box"]["total_weight"] += weight.to_f
        book = Book.find_by_ship_weight(weight)
        content_info = {
          "title:" => book.title, 
          "author:" => book.author,       
          "price:" => book.price,
          "ship_weight:" => book.ship_weight,
          "isbn10:" => book.isbn10,
          "isbn13:" => book.isbn13,
          "total_pages:" => book.total_pages,
          "publisher:" => book.publisher,
          "language:" => book.language
        }
        box["box"]["contents"] << content_info
        @weights.delete_at(index)
      else
        new_box_id = box["box"]["id"] + 1
        create_box(new_box_id, 0)       
      end
    end
  end
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, "Title:" %><br>
    <%= f.text_area :title %>
  </div>

  <div class="field">
    <%= f.label :author, "Author:" %><br>
    <%= f.text_area :author %>
  </div>
  
  <div class="field">
    <%= f.label :price, "Price: " %><br>
    <%= f.text_area :price %>
  </div>

  <div class="field">
    <%= f.label :ship_weight, "Shipping Weight:" %>lbs<br>
    <%= f.text_area :ship_weight %>
  </div>
  
    <div class="field">
    <%= f.label :isbn10, "ISBN10-" %><br>
    <%= f.text_area :isbn10 %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/index.html.erb
<h1>Listing books</h1><%= link_to 'New Book', new_book_path %>

<% @books.each do |book| %>      
<h2><%= book.title %></h2>
<h3>Author: <%= book.author %></h3>   
<h4>Price: <%= book.price %></h4>
<h5>ISBN-10: <%= book.isbn10 %><h5>
<h5>ISBN-13: <%= book.isbn13 %></h5>
<% unless book.total_pages.nil? %>
  <h5>Total Pages: <%= book.total_pages%></h5>
<%end%> 
<h5>Publisher: <%= book.publisher%></h5>
<h5>Language: <%= book.language %></h5>
<h5>Shipping Weight: <%= book.ship_weight %> lbs</h5>
<%= link_to 'Show', book %>
<%= link_to 'Delete', book, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

<br>
<%= ship_weight_list(@books) %>
<%= JSON.pretty_generate(@boxes).html_safe %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>
<h2><%= @book.title %></h2>
<h3>Author: <%= @book.author %></h3>   
<h4>Price: $<%= @book.price %></h4>
<h5>ISBN-10: <%= @book.isbn10 %><h5>
<h5>ISBN-13: <%= @book.isbn13 %></h5>
<h5>Total Pages: <%= @book.total_pages%></h5>
<h5>Publisher: <%= @book.publisher%></h5>
<h5>Language: <%= @book.language %></h5>
<h5>Shipping Weight: <%= @book.ship_weight %> lbs</h5>

<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookpacker</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>